# Generated by Django 5.0.6 on 2025-12-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_app', '0002_user_date_of_birth_user_display_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
