# Generated by Django 5.2.7 on 2025-12-20 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse_app', '0004_postinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-usage_count'],
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_likes', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_mentions', models.BooleanField(default=True)),
                ('notify_follows', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_reposts', models.BooleanField(default=True)),
                ('notify_post_expiring', models.BooleanField(default=True)),
                ('notify_friend_reminder', models.BooleanField(default=False)),
                ('expiring_threshold', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pulse_app.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('message', 'Message'), ('expire', 'Post Expired'), ('mention', 'Mention'), ('repost', 'Repost'), ('follow_request', 'Follow Request'), ('post_expiring', 'Post Expiring Soon')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type', '-created_at'], name='pulse_app_n_user_id_3b8043_idx'),
        ),
        migrations.AddField(
            model_name='mention',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='pulse_app.comment'),
        ),
        migrations.AddField(
            model_name='mention',
            name='mentioned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mention',
            name='mentioned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mention',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='pulse_app.post'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posthashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pulse_app.hashtag'),
        ),
        migrations.AddField(
            model_name='posthashtag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='pulse_app.post'),
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['mentioned_user', '-created_at'], name='pulse_app_m_mention_b277a8_idx'),
        ),
        migrations.AddIndex(
            model_name='posthashtag',
            index=models.Index(fields=['hashtag', '-created_at'], name='pulse_app_p_hashtag_2d7afd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posthashtag',
            unique_together={('post', 'hashtag')},
        ),
    ]
